namespace Misha.Domain.Applicants;
public sealed class Applicant
{
    private Applicant(){}
    private Applicant(Guid id,Guid tenantId,string externalReference){Id=id;TenantId=tenantId;ExternalReference=externalReference;CreatedAtUtc=DateTimeOffset.UtcNow;}
    public Guid Id{get;private set;} public Guid TenantId{get;private set;} public string ExternalReference{get;private set;}=string.Empty; public string? FirstName{get;private set;} public string? LastName{get;private set;} public DateOnly? DateOfBirth{get;private set;} public string? Nationality{get;private set;} public string? CountryOfBirth{get;private set;} public string? PlaceOfBirth{get;private set;} public string? Gender{get;private set;} public string? Email{get;private set;} public string? PhoneNumber{get;private set;} public DateTimeOffset CreatedAtUtc{get;private set;} public DateTimeOffset? UpdatedAtUtc{get;private set;}
    public bool ProfileCompleted=>!string.IsNullOrWhiteSpace(FirstName)&&!string.IsNullOrWhiteSpace(LastName)&&DateOfBirth.HasValue&&!string.IsNullOrWhiteSpace(Nationality);
    public static Applicant Create(Guid tenantId,string externalReference){if(tenantId==Guid.Empty)throw new ArgumentException("Tenant id is required.",nameof(tenantId));if(string.IsNullOrWhiteSpace(externalReference))throw new ArgumentException("Applicant external reference is required.",nameof(externalReference));var reference=externalReference.Trim();if(reference.Length>200)throw new ArgumentException("Applicant external reference must be 200 characters or fewer.",nameof(externalReference));return new Applicant(Guid.NewGuid(),tenantId,reference);}
    public static Applicant Create(string externalReference)=>new Applicant(Guid.NewGuid(),Guid.Empty,externalReference.Trim());
    public void SetProfile(ApplicantProfile profile){ArgumentNullException.ThrowIfNull(profile);FirstName=Required(profile.FirstName,100,nameof(profile.FirstName));LastName=Required(profile.LastName,100,nameof(profile.LastName));Nationality=Required(profile.Nationality,3,nameof(profile.Nationality)).ToUpperInvariant();if(profile.DateOfBirth>=DateOnly.FromDateTime(DateTime.UtcNow))throw new ArgumentException("Date of birth must be in the past.",nameof(profile.DateOfBirth));DateOfBirth=profile.DateOfBirth;CountryOfBirth=Optional(profile.CountryOfBirth,3)?.ToUpperInvariant();PlaceOfBirth=Optional(profile.PlaceOfBirth,200);Gender=Optional(profile.Gender,32);Email=Optional(profile.Email,320);PhoneNumber=Optional(profile.PhoneNumber,50);UpdatedAtUtc=DateTimeOffset.UtcNow;}
    public void Anonymize(){ExternalReference=$"anonymized:{Id:N}";FirstName=null;LastName=null;DateOfBirth=null;Nationality=null;CountryOfBirth=null;PlaceOfBirth=null;Gender=null;Email=null;PhoneNumber=null;UpdatedAtUtc=DateTimeOffset.UtcNow;}
    private static string Required(string v,int max,string p){if(string.IsNullOrWhiteSpace(v))throw new ArgumentException("Value is required.",p);var n=v.Trim();if(n.Length>max)throw new ArgumentException($"Value must be {max} characters or fewer.",p);return n;} private static string? Optional(string? v,int max){if(string.IsNullOrWhiteSpace(v))return null;var n=v.Trim();if(n.Length>max)throw new ArgumentException($"Value must be {max} characters or fewer.");return n;}
}
public sealed record ApplicantProfile(string FirstName,string LastName,DateOnly DateOfBirth,string Nationality,string? CountryOfBirth,string? PlaceOfBirth,string? Gender,string? Email,string? PhoneNumber);
