using Microsoft.EntityFrameworkCore;
using MishaApplication = Misha.Domain.Applications.Application;
using Misha.Domain.Applicants;
using Misha.Domain.Applications;
using Misha.Domain.Decisions;
using Misha.Domain.Documents;
using Misha.Domain.Etas;
using Misha.Domain.ManualReviews;
using Misha.Domain.Notifications;
using Misha.Domain.Payments;
using Misha.Domain.Watchlists;
namespace Misha.Infrastructure.Persistence;
public sealed class MishaDbContext(DbContextOptions<MishaDbContext> options) : DbContext(options)
{
 public DbSet<Applicant> Applicants=>Set<Applicant>(); public DbSet<MishaApplication> Applications=>Set<MishaApplication>(); public DbSet<ApplicationLifecycleAudit> ApplicationLifecycleAudits=>Set<ApplicationLifecycleAudit>(); public DbSet<DecisionAudit> DecisionAudits=>Set<DecisionAudit>(); public DbSet<DocumentArtifact> DocumentArtifacts=>Set<DocumentArtifact>(); public DbSet<PassportDocument> PassportDocuments=>Set<PassportDocument>(); public DbSet<WatchlistCheck> WatchlistChecks=>Set<WatchlistCheck>(); public DbSet<Payment> Payments=>Set<Payment>(); public DbSet<Eta> Etas=>Set<Eta>(); public DbSet<EtaAudit> EtaAudits=>Set<EtaAudit>(); public DbSet<ManualReviewCase> ManualReviewCases=>Set<ManualReviewCase>(); public DbSet<Notification> Notifications=>Set<Notification>(); public DbSet<OutboxMessage> OutboxMessages=>Set<OutboxMessage>();
 protected override void OnModelCreating(ModelBuilder m)
 {
  var a=m.Entity<Applicant>(); a.ToTable("applicants"); a.HasKey(x=>x.Id); a.Property(x=>x.ExternalReference).HasMaxLength(200).IsRequired(); a.Property(x=>x.TenantId).HasMaxLength(200); a.Property(x=>x.FirstName).HasMaxLength(100); a.Property(x=>x.LastName).HasMaxLength(100); a.Property(x=>x.Nationality).HasMaxLength(3); a.Property(x=>x.CountryOfBirth).HasMaxLength(3); a.Property(x=>x.PlaceOfBirth).HasMaxLength(200); a.Property(x=>x.Gender).HasMaxLength(32); a.Property(x=>x.Email).HasMaxLength(320); a.Property(x=>x.PhoneNumber).HasMaxLength(50); a.Property(x=>x.CreatedAtUtc).IsRequired(); a.Ignore(x=>x.ProfileCompleted); a.HasIndex(x=>new { x.TenantId,x.ExternalReference }).IsUnique();
  var x=m.Entity<MishaApplication>(); x.ToTable("applications"); x.HasKey(y=>y.Id); x.Property(y=>y.ApplicantId).IsRequired(); x.Property(y=>y.ApplicantReference).HasMaxLength(200).IsRequired(); x.Property(y=>y.IdempotencyKey).HasMaxLength(200); x.Property(y=>y.TenantId).HasMaxLength(200); x.Property(y=>y.Status).HasConversion<string>().HasMaxLength(32).IsRequired(); x.Property(y=>y.CreatedAtUtc).IsRequired(); x.Property(y=>y.RefusalReason).HasMaxLength(1000); x.Property(y=>y.Version).IsRowVersion(); x.HasIndex(y=>y.ApplicantId); x.HasIndex(y=>y.ApplicantReference); x.HasIndex(y=>y.TenantId); x.HasIndex(y=>y.Status); x.HasIndex(y=>y.IdempotencyKey).IsUnique(); x.HasOne<Applicant>().WithMany().HasForeignKey(y=>y.ApplicantId).OnDelete(DeleteBehavior.Restrict);
  var l=m.Entity<ApplicationLifecycleAudit>(); l.ToTable("application_lifecycle_audits"); l.HasKey(y=>y.Id); l.Property(y=>y.FromStatus).HasConversion<string>().HasMaxLength(32); l.Property(y=>y.ToStatus).HasConversion<string>().HasMaxLength(32).IsRequired(); l.Property(y=>y.Reason).HasMaxLength(1000); l.Property(y=>y.ActorReference).HasMaxLength(200).IsRequired(); l.Property(y=>y.OccurredAtUtc).IsRequired(); l.HasIndex(y=>new { y.ApplicationId,y.OccurredAtUtc });
  var d=m.Entity<DecisionAudit>(); d.ToTable("decision_audits"); d.HasKey(y=>y.Id); d.Property(y=>y.PolicyVersion).HasMaxLength(50).IsRequired(); d.Property(y=>y.PolicyDecision).HasMaxLength(32).IsRequired(); d.Property(y=>y.Decision).HasMaxLength(32).IsRequired(); d.Property(y=>y.ReasonsJson).HasColumnType("jsonb").IsRequired(); d.Property(y=>y.ActorReference).HasMaxLength(200).IsRequired(); d.Property(y=>y.CreatedAtUtc).IsRequired(); d.HasIndex(y=>new { y.ApplicationId,y.CreatedAtUtc });
  var doc=m.Entity<DocumentArtifact>(); doc.ToTable("document_artifacts"); doc.HasKey(y=>y.Id); doc.Property(y=>y.DocumentType).HasConversion<string>().HasMaxLength(32).IsRequired(); doc.Property(y=>y.FileName).HasMaxLength(255).IsRequired(); doc.Property(y=>y.ContentType).HasMaxLength(200).IsRequired(); doc.Property(y=>y.SizeBytes).IsRequired(); doc.Property(y=>y.Sha256).HasMaxLength(64).IsRequired(); doc.Property(y=>y.StorageKey).HasMaxLength(500).IsRequired(); doc.Property(y=>y.CreatedAtUtc).IsRequired(); doc.HasIndex(y=>new { y.ApplicationId,y.CreatedAtUtc }); doc.HasIndex(y=>y.Sha256);
  var p=m.Entity<PassportDocument>(); p.ToTable("passport_documents"); p.HasKey(y=>y.Id); p.Property(y=>y.DocumentNumber).HasMaxLength(50).IsRequired(); p.Property(y=>y.IssuingCountry).HasMaxLength(3).IsRequired(); p.Property(y=>y.Surname).HasMaxLength(200).IsRequired(); p.Property(y=>y.GivenNames).HasMaxLength(200).IsRequired(); p.Property(y=>y.Nationality).HasMaxLength(3).IsRequired(); p.HasIndex(y=>y.ApplicationId).IsUnique(); p.HasIndex(y=>y.DocumentNumber);
  var w=m.Entity<WatchlistCheck>(); w.ToTable("watchlist_checks"); w.HasKey(y=>y.Id); w.Property(y=>y.Provider).HasMaxLength(100).IsRequired(); w.Property(y=>y.Decision).HasConversion<string>().HasMaxLength(32).IsRequired(); w.Property(y=>y.MatchReference).HasMaxLength(200); w.Property(y=>y.ErrorMessage).HasMaxLength(1000); w.HasIndex(y=>new { y.ApplicationId,y.CreatedAtUtc });
  var pay=m.Entity<Payment>(); pay.ToTable("payments"); pay.HasKey(y=>y.Id); pay.Property(y=>y.AmountMinor).IsRequired(); pay.Property(y=>y.Currency).HasMaxLength(3).IsRequired(); pay.Property(y=>y.Status).HasConversion<string>().HasMaxLength(32).IsRequired(); pay.Property(y=>y.Provider).HasMaxLength(100); pay.Property(y=>y.ProviderReference).HasMaxLength(200); pay.Property(y=>y.ActionUrl).HasMaxLength(1000); pay.Property(y=>y.FailureReason).HasMaxLength(1000); pay.Property(y=>y.CreatedAtUtc).IsRequired(); pay.HasIndex(y=>new { y.ApplicationId,y.CreatedAtUtc }); pay.HasIndex(y=>y.ProviderReference);
  var eta=m.Entity<Eta>(); eta.ToTable("etas"); eta.HasKey(y=>y.Id); eta.Property(y=>y.EtaNumber).HasMaxLength(32).IsRequired(); eta.Property(y=>y.VerificationTokenHash).HasMaxLength(64).IsRequired(); eta.Property(y=>y.Status).HasConversion<string>().HasMaxLength(32).IsRequired(); eta.Property(y=>y.IssuedAtUtc).IsRequired(); eta.Property(y=>y.ExpiresAtUtc).IsRequired(); eta.Property(y=>y.RevocationReason).HasMaxLength(1000); eta.HasIndex(y=>y.ApplicationId).IsUnique(); eta.HasIndex(y=>y.EtaNumber).IsUnique(); eta.HasIndex(y=>y.VerificationTokenHash).IsUnique();
  var ea=m.Entity<EtaAudit>(); ea.ToTable("eta_audits"); ea.HasKey(y=>y.Id); ea.Property(y=>y.EtaNumber).HasMaxLength(32); ea.Property(y=>y.EventType).HasConversion<string>().HasMaxLength(32).IsRequired(); ea.Property(y=>y.Outcome).HasMaxLength(32).IsRequired(); ea.Property(y=>y.ActorReference).HasMaxLength(200).IsRequired(); ea.Property(y=>y.OccurredAtUtc).IsRequired(); ea.HasIndex(y=>new { y.EtaId,y.OccurredAtUtc }); ea.HasIndex(y=>new { y.ApplicationId,y.OccurredAtUtc }); ea.HasIndex(y=>new { y.EventType,y.OccurredAtUtc });
  var mr=m.Entity<ManualReviewCase>(); mr.ToTable("manual_review_cases"); mr.HasKey(y=>y.Id); mr.Property(y=>y.Status).HasConversion<string>().HasMaxLength(32).IsRequired(); mr.Property(y=>y.Trigger).HasMaxLength(100).IsRequired(); mr.Property(y=>y.Reason).HasMaxLength(2000).IsRequired(); mr.Property(y=>y.AssignedToActorReference).HasMaxLength(200); mr.Property(y=>y.Resolution).HasConversion<string>().HasMaxLength(32); mr.Property(y=>y.ResolutionReason).HasMaxLength(2000); mr.Property(y=>y.ResolvedByActorReference).HasMaxLength(200); mr.Property(y=>y.CreatedAtUtc).IsRequired(); mr.HasIndex(y=>new { y.Status,y.CreatedAtUtc }); mr.HasIndex(y=>new { y.ApplicationId,y.CreatedAtUtc });
  var n=m.Entity<Notification>(); n.ToTable("notifications"); n.HasKey(y=>y.Id); n.Property(y=>y.RecipientReference).HasMaxLength(200).IsRequired(); n.Property(y=>y.Channel).HasMaxLength(32).IsRequired(); n.Property(y=>y.Template).HasMaxLength(100).IsRequired(); n.Property(y=>y.Payload).HasColumnType("text").IsRequired(); n.Property(y=>y.Status).HasConversion<string>().HasMaxLength(32).IsRequired(); n.Property(y=>y.LastError).HasMaxLength(2000); n.Property(y=>y.CreatedAtUtc).IsRequired(); n.HasIndex(y=>new { y.Status,y.CreatedAtUtc }); n.HasIndex(y=>new { y.ApplicationId,y.CreatedAtUtc });
  var o=m.Entity<OutboxMessage>(); o.ToTable("outbox_messages"); o.HasKey(y=>y.Id); o.Property(y=>y.EventType).HasMaxLength(200).IsRequired(); o.Property(y=>y.Payload).HasColumnType("jsonb").IsRequired(); o.Property(y=>y.OccurredAtUtc).IsRequired(); o.Property(y=>y.PublishedAtUtc); o.Property(y=>y.AttemptCount).IsRequired(); o.Property(y=>y.LastAttemptAtUtc); o.Property(y=>y.LastError).HasMaxLength(2000); o.HasIndex(y=>new { y.PublishedAtUtc,y.OccurredAtUtc }); o.HasIndex(y=>new { y.AggregateId,y.OccurredAtUtc });
 }
}
